
###
{ handle: 1,
  type: 'script',
  name: 'console.js',
  id: 58,
  lineOffset: 0,
  columnOffset: 0,
  lineCount: 79,
  sourceStart: '(function (exports, require, module, __filename, __dirname) { // Copyright Joyen',
  sourceLength: 2348,
  scriptType: 2,
  compilationType: 0,
  context: { ref: 0 },
  text: 'console.js (lines: 79)',
  source: '......................................' }
###

###
  { handle: 92,
    type: 'script',
    name: '/Users/jankrems/Projects/bugger/node_modules/coffee-script-redux/lib/nodes.js',
    id: 35,
    lineOffset: 0,
    columnOffset: 0,
    lineCount: 587,
    sourceStart: '(function (exports, require, module, __filename, __dirname) { // Generated by Co',
    sourceLength: 15833,
    scriptType: 2,
    compilationType: 0,
    context: { ref: 91 },
    text: '/Users/jankrems/Projects/bugger/node_modules/coffee-script-redux/lib/nodes.js (lines: 587)' }
###

module.exports = (refs) -> (body) ->
  script = {
    scriptId: body.id.toString()
    url: 'file://' + body.name
    startLine: body.lineOffset
    # endLine: body.lineCount
    # endColumn
    isContentScript: false
    # sourceMapURL
    scriptSource: body.source
  }

  return script
