// Generated by CoffeeScript 2.0.0-beta5
var createServer, server, WebSocketServer;
createServer = require('http').createServer;
WebSocketServer = require('websocket').server;
module.exports = function () {
  var server;
  server = createServer(function (req, res) {
    res.write(server.DEFAULT_URL + '\n');
    return res.end();
  });
  server.websocket = new WebSocketServer({
    httpServer: server,
    autoAcceptConnections: true
  });
  server.on('listening', function () {
    var address, cache$, port;
    cache$ = this.address();
    address = cache$.address;
    port = cache$.port;
    this.QUERY_STRING = 'ws=' + address + ':' + port + '/websocket';
    return this.DEFAULT_URL = 'chrome://devtools/devtools.html?' + this.QUERY_STRING;
  });
  return server;
};
if (!module.parent) {
  server = module.exports();
  server.listen(8058, function () {
    return console.log('Open Devtools:\n' + this.DEFAULT_URL);
  });
}
