// Generated by CoffeeScript 2.0.0-beta5
var EventEmitter;
EventEmitter = require('events').EventEmitter;
module.exports = function (agentContext) {
  var ApplicationCache;
  ApplicationCache = new EventEmitter;
  ApplicationCache.getFramesWithManifests = function (param$, cb) {
    void 0;
  };
  ApplicationCache.enable = function (param$, cb) {
    void 0;
  };
  ApplicationCache.getManifestForFrame = function (param$, cb) {
    var frameId;
    frameId = param$.frameId;
  };
  ApplicationCache.getApplicationCacheForFrame = function (param$, cb) {
    var frameId;
    frameId = param$.frameId;
  };
  ApplicationCache.emit_applicationCacheStatusUpdated = function (params) {
    var notification;
    notification = {
      params: params,
      method: 'ApplicationCache.applicationCacheStatusUpdated'
    };
    return this.emit('notification', notification);
  };
  ApplicationCache.emit_networkStateUpdated = function (params) {
    var notification;
    notification = {
      params: params,
      method: 'ApplicationCache.networkStateUpdated'
    };
    return this.emit('notification', notification);
  };
  ApplicationCache.ApplicationCacheResource = {
    id: 'ApplicationCacheResource',
    type: 'object',
    description: 'Detailed application cache resource information.',
    properties: [
      {
        name: 'url',
        type: 'string',
        description: 'Resource url.'
      },
      {
        name: 'size',
        type: 'integer',
        description: 'Resource size.'
      },
      {
        name: 'type',
        type: 'string',
        description: 'Resource type.'
      }
    ]
  };
  ApplicationCache.ApplicationCache = {
    id: 'ApplicationCache',
    type: 'object',
    description: 'Detailed application cache information.',
    properties: [
      {
        name: 'manifestURL',
        type: 'string',
        description: 'Manifest URL.'
      },
      {
        name: 'size',
        type: 'number',
        description: 'Application cache size.'
      },
      {
        name: 'creationTime',
        type: 'number',
        description: 'Application cache creation time.'
      },
      {
        name: 'updateTime',
        type: 'number',
        description: 'Application cache update time.'
      },
      {
        name: 'resources',
        type: 'array',
        items: { $ref: 'ApplicationCacheResource' },
        description: 'Application cache resources.'
      }
    ]
  };
  ApplicationCache.FrameWithManifest = {
    id: 'FrameWithManifest',
    type: 'object',
    description: 'Frame identifier - manifest URL pair.',
    properties: [
      {
        name: 'frameId',
        $ref: 'Network.FrameId',
        description: 'Frame identifier.'
      },
      {
        name: 'manifestURL',
        type: 'string',
        description: 'Manifest URL.'
      },
      {
        name: 'status',
        type: 'integer',
        description: 'Application cache status.'
      }
    ]
  };
  return ApplicationCache;
};
