// Generated by CoffeeScript 2.0.0-beta5
var agentContext, domainNames, domains, EventEmitter, loadDomainNames, readdirSync;
EventEmitter = require('events').EventEmitter;
readdirSync = require('fs').readdirSync;
module.exports = domains = new EventEmitter;
agentContext = { debugClient: null };
loadDomainNames = function () {
  return readdirSync(__dirname).filter(function (f) {
    return /^[A-Z].*\.js/.test(f);
  }).map(function (f) {
    return f.replace('.js', '');
  });
};
domainNames = loadDomainNames();
domains.handle = function (request) {
  var agent, cache$, cache$1, callback, command, domain, error, method, params;
  method = request.method;
  cache$ = method.split('.');
  domain = cache$[0];
  command = cache$[1];
  agent = domains[domain];
  if (!(null != agent)) {
    error = new Error('Domain ' + domain + ' not found');
    return domains.emit('error', error);
  }
  if (!(typeof agent[command] === 'function')) {
    error = new Error('Unknown command: ' + domain + '.' + command);
    return domains.emit('error', error);
  }
  cache$1 = request;
  params = cache$1.params;
  callback = cache$1.callback;
  return agent[command](params, callback);
};
domains.unload = function () {
  var agent, domain;
  for (var i$ = 0, length$ = domainNames.length; i$ < length$; ++i$) {
    domain = domainNames[i$];
    agent = domains[domain];
    if (null != agent) {
      agent.removeAllListeners();
      if (typeof agent.disable === 'function')
        agent.disable({}, function () {
        });
    }
    delete domains[domain];
  }
  return null;
};
domains.load = function (param$) {
  var agent, debugClient, domain;
  debugClient = param$.debugClient;
  domains.unload();
  agentContext = { debugClient: debugClient };
  for (var i$ = 0, length$ = domainNames.length; i$ < length$; ++i$) {
    domain = domainNames[i$];
    agent = domains[domain] = require('./' + domain)(agentContext);
    agent.on('notification', function (notification) {
      return domains.emit('notification', notification);
    });
  }
  return null;
};
