// Generated by CoffeeScript 2.0.0-beta5
module.exports = function (refs) {
  return function (body) {
    return {
      scriptId: body.id.toString(),
      url: body.name,
      startLine: body.lineOffset,
      isContentScript: false,
      scriptSource: body.source
    };
  };
};
