// Generated by CoffeeScript 2.0.0-beta4
var agents, entryScript;
entryScript = require('./forked/entry_script');
agents = {
  Timeline: {
    start: function (param$, cb, channel) {
      var maxCallStackDepth;
      maxCallStackDepth = param$.maxCallStackDepth;
      entryScript.proc.send({ method: 'Timeline.start' });
      return cb(null, true);
    },
    stop: function (cb, channel) {
      entryScript.proc.send({ method: 'Timeline.stop' });
      return cb(null, true);
    }
  },
  Debugger: require('./agents/debugger'),
  Console: require('./agents/console'),
  Runtime: require('./agents/runtime'),
  Network: require('./agents/network')
};
module.exports = {
  invoke: function (agentName, functionName, args) {
    var agent, handlerFn;
    agent = agents[agentName];
    handlerFn = null != agent ? agent[functionName] : void 0;
    if (handlerFn) {
      return handlerFn.apply(agent, args);
    } else {
      return entryScript.delegate('' + agentName + '.' + functionName, args[0], args[1]);
    }
  }
};
