// Generated by CoffeeScript 2.0.0-beta6
var bugger, buggerDefaults, bugScript, defaults, domains, EventEmitter, inspectorServer, omit, parallel;
EventEmitter = require('events').EventEmitter;
parallel = require('async').parallel;
cache$ = require('underscore');
omit = cache$.omit;
defaults = cache$.defaults;
bugScript = require('./bug-script');
domains = require('./domains');
inspectorServer = require('./inspector');
buggerDefaults = {
  debugBreak: true,
  webport: 8058,
  webhost: '127.0.0.1',
  hang: true,
  stfu: false,
  language: null,
  propes: null
};
bugger = function (buggerOpts) {
  var buggerLog, cache$1, debugBreak, forwardErrors, hang, language, probes, run, startScript, startServer, stfu, webhost, webport, wire, wireStdIO, wrapEmitter;
  if (null == buggerOpts)
    buggerOpts = {};
  defaults(buggerOpts, buggerDefaults);
  cache$1 = buggerOpts;
  debugBreak = cache$1.debugBreak;
  webport = cache$1.webport;
  webhost = cache$1.webhost;
  hang = cache$1.hang;
  stfu = cache$1.stfu;
  language = cache$1.language;
  probes = cache$1.probes;
  buggerLog = stfu ? function () {
  } : function (message) {
    return console.error(message);
  };
  startServer = function (cb) {
    var inspector;
    inspector = inspectorServer();
    return inspector.listen(webport, webhost, function () {
      return cb(null, inspector);
    });
  };
  wrapEmitter = new EventEmitter;
  forwardErrors = function (internalObjects) {
    internalObjects = 1 <= arguments.length ? [].slice.call(arguments, 0) : [];
    return function (accum$) {
      var internalObj;
      for (var i$ = 0, length$ = internalObjects.length; i$ < length$; ++i$) {
        internalObj = internalObjects[i$];
        accum$.push(internalObj.on('error', function (err) {
          return wrapEmitter.emit('error', err);
        }));
      }
      return accum$;
    }.call(this, []);
  };
  startScript = function (script, scriptArgs, options) {
    return function (cb) {
      return bugScript(script, scriptArgs, options, cb);
    };
  };
  wireStdIO = function (forked) {
    forked.stdout.pipe(process.stdout);
    forked.stderr.pipe(process.stderr);
    return process.stdin.pipe(forked.stdin);
  };
  wire = function (param$) {
    var cache$2, debugClient, forked, inspector;
    {
      cache$2 = param$;
      inspector = cache$2.inspector;
      forked = cache$2.forked;
      debugClient = cache$2.debugClient;
      domains = cache$2.domains;
    }
    wireStdIO(forked);
    forwardErrors(debugClient, domains, forked, inspector);
    domains.load({
      debugClient: debugClient,
      forked: forked
    });
    inspector.on('request', domains.handle);
    domains.on('notification', inspector.dispatchEvent);
    forked.on('exit', function (exitCode) {
      if (hang) {
        return buggerLog('[bugger] Process exit with status ' + exitCode);
      } else {
        return process.exit(exitCode);
      }
    });
    return forked.on('message', function (message) {
      var method, params;
      if (null != message.method) {
        method = message.method;
        params = omit(message, 'method');
        return domains.handle({
          method: method,
          params: params
        });
      }
    });
  };
  wrapEmitter.run = run = function (script, scriptArgs) {
    var tasks;
    if (null == scriptArgs)
      scriptArgs = [];
    tasks = [
      startServer,
      startScript(script, scriptArgs, buggerOpts)
    ];
    return parallel(tasks, function (err, param$) {
      var cache$2, forked, inspector;
      {
        cache$2 = param$;
        inspector = cache$2[0];
        forked = cache$2[1];
      }
      if (null != err)
        throw err;
      return forked.on('debugClient', function (debugClient) {
        var argString;
        wire({
          inspector: inspector,
          forked: forked,
          debugClient: debugClient,
          domains: domains
        });
        argString = scriptArgs.map(function (arg) {
          return JSON.stringify(arg);
        }).join(' ');
        buggerLog('[bugger] Debugging ' + script + ' ' + argString);
        return buggerLog('[bugger] ' + inspector.DEFAULT_URL);
      });
    });
  };
  return wrapEmitter;
};
module.exports = bugger;
if (!(null != module.parent))
  bugger().run('examples/simple.js');
