// Generated by CoffeeScript 2.0.0-beta5
var bugger, bugScript, domains, inspectorServer, parallel;
parallel = require('async').parallel;
bugScript = require('./bug-script');
domains = require('./domains');
inspectorServer = require('./inspector');
bugger = function (debugBreak, webport, webhost) {
  var run, startScript, startServer, wire, wireStdIO;
  if (null == debugBreak)
    debugBreak = true;
  if (null == webport)
    webport = 8058;
  if (null == webhost)
    webhost = '127.0.0.1';
  startServer = function (cb) {
    var inspector;
    inspector = inspectorServer();
    return inspector.listen(webport, webhost, function () {
      return cb(null, inspector);
    });
  };
  startScript = function (script, scriptArgs, options) {
    return function (cb) {
      return bugScript(script, scriptArgs, options, cb);
    };
  };
  wireStdIO = function (forked) {
    forked.stdout.pipe(process.stdout);
    forked.stderr.pipe(process.stderr);
    return process.stdin.pipe(forked.stdin);
  };
  wire = function (param$) {
    var cache$, debugClient, forked, inspector;
    {
      cache$ = param$;
      inspector = cache$.inspector;
      forked = cache$.forked;
      debugClient = cache$.debugClient;
      domains = cache$.domains;
    }
    wireStdIO(forked);
    debugClient.on('error', function (err) {
      return console.log('[bugger] [error]', err.message);
    });
    domains.load({ debugClient: debugClient });
    inspector.on('request', domains.handle);
    return domains.on('notification', inspector.dispatchEvent);
  };
  run = function (script, scriptArgs) {
    var tasks;
    if (null == scriptArgs)
      scriptArgs = [];
    tasks = [
      startServer,
      startScript(script, scriptArgs, { debugBreak: debugBreak })
    ];
    return parallel(tasks, function (err, param$) {
      var cache$, forked, inspector;
      {
        cache$ = param$;
        inspector = cache$[0];
        forked = cache$[1];
      }
      return forked.on('debugClient', function (debugClient) {
        wire({
          inspector: inspector,
          forked: forked,
          debugClient: debugClient,
          domains: domains
        });
        console.log('[bugger] Debugging ' + script, scriptArgs.join(' '));
        return console.log('[bugger] ' + inspector.DEFAULT_URL);
      });
    });
  };
  return { run: run };
};
module.exports = bugger;
if (!(null != module.parent))
  bugger().run('examples/simple.js');
