// Generated by CoffeeScript 2.0.0-beta4
var _responseContentCache, NetworkAgent;
_responseContentCache = {};
module.exports = NetworkAgent = {
  cacheResponseContent: function (param$) {
    var cache$, chunk, requestId;
    {
      cache$ = param$;
      requestId = cache$.requestId;
      chunk = cache$.chunk;
    }
    return _responseContentCache[requestId] = (null != _responseContentCache[requestId] ? _responseContentCache[requestId] : '') + chunk.toString();
  },
  getResponseBody: function (param$, cb) {
    var requestId;
    requestId = param$.requestId;
    return cb(null, _responseContentCache[requestId].toString(), false);
  }
};
