// Generated by CoffeeScript 2.0.0-beta5
var coffee, compile, compileString, load, Module;
coffee = require('coffee-script-redux');
Module = require('module');
coffee.register();
compile = function (filename, input, cb) {
  var cache$, code, csAst, jsAst, map;
  csAst = coffee.parse(input, { raw: true });
  jsAst = coffee.compile(csAst, { bare: true });
  cache$ = coffee.jsWithSourceMap(jsAst, filename, { compact: true });
  code = cache$.code;
  map = cache$.map;
  return cb(null, {
    code: code,
    map: map
  });
};
compileString = function (input) {
  var csAst, jsAst;
  csAst = coffee.parse(input, { raw: true });
  jsAst = coffee.compile(csAst, { bare: true });
  return coffee.js(jsAst, 'repl', { compact: true });
};
load = function (scriptContext) {
  return scriptContext.compilers['.coffee'] = {
    compile: compile,
    compileString: compileString
  };
};
module.exports = {
  compile: compile,
  compileString: compileString,
  load: load
};
