// Generated by CoffeeScript 2.0.0-beta5
var load, TimelineProbe;
TimelineProbe = function () {
  var __time, __timeEnd, timerStarts;
  timerStarts = {};
  console.timeStamp = function (message) {
    if (null == message)
      message = 'console.timeStamp';
    return process.send({
      method: 'Timeline.emit_eventRecorded',
      record: {
        type: 'TimeStamp',
        startTime: Date.now(),
        data: { message: message }
      }
    });
  };
  __time = console.time;
  console.time = function (message) {
    var startTime;
    startTime = timerStarts[message] = Date.now();
    process.send({
      method: 'Timeline.emit_eventRecorded',
      record: {
        type: 'Time',
        startTime: startTime,
        data: { message: message }
      }
    });
    return __time.apply(console, arguments);
  };
  __timeEnd = console.timeEnd;
  return console.timeEnd = function (message) {
    var startTime;
    startTime = timerStarts[message];
    process.send({
      method: 'Timeline.emit_eventRecorded',
      record: {
        type: 'TimeEnd',
        startTime: Date.now(),
        data: { message: message }
      }
    });
    return __timeEnd.apply(console, arguments);
  };
};
load = function (scriptContext, safe) {
  var Timeline;
  if (null == safe)
    safe = false;
  if (safe)
    return;
  return Timeline = TimelineProbe();
};
module.exports = { load: load };
