// Generated by CoffeeScript 2.0.0-beta5
var toTimeline;
module.exports = toTimeline = function (type, record) {
  record.type = type;
  if (null != record.startTime)
    record.startTime;
  else
    record.startTime = Date.now();
  if (null != record.endTime)
    record.endTime;
  else
    record.endTime = Date.now();
  record.usedHeapSize = process.memoryUsage().heapUsed;
  return process.send({
    method: 'Timeline.emit_eventRecorded',
    record: record
  });
};
