// Generated by CoffeeScript 2.0.0-beta4
var callbacks, lastId;
lastId = 1;
callbacks = {};
module.exports.create = function () {
  return {
    wrap: function (callback) {
      callbacks[lastId] = callback || function () {
      };
      return lastId++;
    },
    processResponse: function (callbackId, args) {
      var callback;
      callback = callbacks[callbackId];
      callback.apply(null, args);
      return delete callbacks[callbackId];
    },
    removeResponseCallbackEntry: function (callbackId) {
      return delete callbacks[callbackId];
    }
  };
};
