// Generated by CoffeeScript 2.0.0-beta5
var knownTypes, type, typeHandlers;
module.exports = function (body, refs, options) {
  var cache$, generatePreview, returnByValue;
  cache$ = options;
  generatePreview = cache$.generatePreview;
  returnByValue = cache$.returnByValue;
  return null;
};
typeHandlers = {};
knownTypes = [
  'undefined',
  'null',
  'boolean',
  'number',
  'string',
  'object',
  'function',
  'frame',
  'scope',
  'script',
  'error'
];
for (var i$ = 0, length$ = knownTypes.length; i$ < length$; ++i$) {
  type = knownTypes[i$];
  typeHandlers[type] = require('./' + type);
}
