// Generated by CoffeeScript 2.0.0-beta5
var debugClient, EventEmitter;
EventEmitter = require('events').EventEmitter;
module.exports = debugClient = function (debugConnection) {
  var client;
  client = new EventEmitter;
  return client;
};
