// Generated by CoffeeScript 2.0.0-beta5
var ErrorObjectFromMessage, RemoteScript;
RemoteScript = require('../remote-script');
ErrorObjectFromMessage = require('../remote-object').ErrorObjectFromMessage;
module.exports = function (debugClient) {
  var clearbreakpoint;
  clearbreakpoint = function (breakpointId, cb) {
    var params;
    params = { breakpoint: breakpointId };
    return debugClient.sendRequest('clearbreakpoint', params, function (err, response) {
      var body, cache$, message, refs, success;
      cache$ = response;
      refs = cache$.refs;
      body = cache$.body;
      success = cache$.success;
      message = cache$.message;
      if (success) {
        return cb(null, { breakpointId: body.breakpoint });
      } else {
        return cb(ErrorObjectFromMessage(options)(refs)(message));
      }
    });
  };
  return clearbreakpoint;
};
