// Generated by CoffeeScript 2.0.0-beta5
var ErrorObjectFromMessage, RemoteScript;
RemoteScript = require('../remote-script');
ErrorObjectFromMessage = require('../remote-object').ErrorObjectFromMessage;
module.exports = function (debugClient) {
  var continueCmd;
  continueCmd = function (stepaction, cb) {
    var params;
    params = { stepaction: stepaction };
    if ('function' === typeof stepaction) {
      cb = stepaction;
      params = {};
    }
    return debugClient.sendRequest('continue', params, function (err, response) {
      var body, cache$, message, refs, success;
      cache$ = response;
      refs = cache$.refs;
      body = cache$.body;
      success = cache$.success;
      message = cache$.message;
      if (success) {
        return cb();
      } else {
        return cb(ErrorObjectFromMessage({})(refs)(message));
      }
    });
  };
  return continueCmd;
};
