// Generated by CoffeeScript 2.0.0-beta5
module.exports = function (debugClient) {
  return {
    evaluate: require('./evaluate')(debugClient),
    scripts: require('./scripts')(debugClient),
    backtrace: require('./backtrace')(debugClient),
    scopes: require('./scopes')(debugClient),
    'continue': require('./continue')(debugClient),
    suspend: require('./suspend')(debugClient),
    setbreakpoint: require('./setbreakpoint')(debugClient),
    clearbreakpoint: require('./clearbreakpoint')(debugClient),
    setexceptionbreak: require('./setexceptionbreak')(debugClient),
    lookup: require('./lookup')(debugClient),
    changelive: require('./changelive')(debugClient)
  };
};
