// Generated by CoffeeScript 2.0.0-beta5
module.exports = function (debugClient) {
  return {
    evaluate: require('./evaluate')(debugClient),
    scripts: require('./scripts')(debugClient),
    backtrace: require('./backtrace')(debugClient),
    scopes: require('./scopes')(debugClient),
    setexceptionbreak: require('./setexceptionbreak')(debugClient),
    lookup: require('./lookup')(debugClient)
  };
};
