// Generated by CoffeeScript 2.0.0-beta7
var ErrorObjectFromMessage, RemoteObject, RemoteScript, series;
series = require('async').series;
RemoteScript = require('../remote-script');
cache$ = require('../remote-object');
ErrorObjectFromMessage = cache$.ErrorObjectFromMessage;
RemoteObject = cache$.RemoteObject;
module.exports = function (debugClient) {
  var scopes;
  scopes = function (options, cb) {
    return debugClient.sendRequest('scopes', options, function (err, response) {
      var body, cache$1, cache$2, fromScope, message, refMap, success, toScope, totalScopes;
      cache$1 = response;
      refMap = cache$1.refMap;
      body = cache$1.body;
      success = cache$1.success;
      message = cache$1.message;
      if (success) {
        cache$2 = body;
        fromScope = cache$2.fromScope;
        toScope = cache$2.toScope;
        totalScopes = cache$2.totalScopes;
        scopes = cache$2.scopes;
        scopes = scopes.map(function (scope) {
          scope.object = RemoteObject({})(refMap)(scope.object);
          scope.object.objectId = 'scope:' + options.frameNumber + ':' + scope.index;
          scope.type = function () {
            switch (scope.type) {
            case 0:
              return 'global';
            case 1:
              return 'local';
            case 2:
              return 'with';
            case 3:
              return 'closure';
            case 4:
              return 'catch';
            default:
              return 'unknown';
            }
          }.call(this);
          return scope;
        });
        return cb(null, {
          fromScope: fromScope,
          toScope: toScope,
          totalScopes: totalScopes,
          scopes: scopes
        });
      } else {
        return cb(ErrorObjectFromMessage(options)(refMap)(message));
      }
    });
  };
  return scopes;
};
