// Generated by CoffeeScript 2.0.0-beta5
var ErrorObjectFromMessage, RemoteObject, RemoteScript, series;
series = require('async').series;
RemoteScript = require('../remote-script');
cache$ = require('../remote-object');
ErrorObjectFromMessage = cache$.ErrorObjectFromMessage;
RemoteObject = cache$.RemoteObject;
module.exports = function (debugClient) {
  var scopes;
  scopes = function (options, cb) {
    return debugClient.sendRequest('scopes', options, function (err, response) {
      var body, cache$1, cache$2, fromScope, message, refs, success, toScope, totalScopes;
      cache$1 = response;
      refs = cache$1.refs;
      body = cache$1.body;
      success = cache$1.success;
      message = cache$1.message;
      if (success) {
        cache$2 = body;
        fromScope = cache$2.fromScope;
        toScope = cache$2.toScope;
        totalScopes = cache$2.totalScopes;
        scopes = cache$2.scopes;
        scopes = scopes.map(function (scope) {
          scope.object = RemoteObject({})(refs)(scope.object);
          scope.object.objectId = 'scope:' + options.frameNumber + ':' + scope.index;
          return scope;
        });
        return cb(null, {
          fromScope: fromScope,
          toScope: toScope,
          totalScopes: totalScopes,
          scopes: scopes
        });
      } else {
        return cb(ErrorObjectFromMessage(options)(refs)(message));
      }
    });
  };
  return scopes;
};
