// Generated by CoffeeScript 2.0.0-beta7
var ErrorObjectFromMessage, RemoteScript;
RemoteScript = require('../remote-script');
ErrorObjectFromMessage = require('../remote-object').ErrorObjectFromMessage;
module.exports = function (debugClient) {
  var setbreakpoint;
  setbreakpoint = function (options, cb) {
    var breakpointDesc, cache$, columnNumber, condition, lineNumber, url, urlRegex;
    cache$ = options;
    lineNumber = cache$.lineNumber;
    url = cache$.url;
    urlRegex = cache$.urlRegex;
    columnNumber = cache$.columnNumber;
    condition = cache$.condition;
    breakpointDesc = {
      line: lineNumber,
      column: columnNumber,
      condition: condition
    };
    if (null != urlRegex) {
      breakpointDesc.type = 'scriptRegExp';
      breakpointDesc.target = urlRegex;
    } else {
      breakpointDesc.type = 'script';
      breakpointDesc.target = url.replace(/^file:\/\//, '');
    }
    return debugClient.sendRequest('setbreakpoint', breakpointDesc, function (err, response) {
      var body, breakpointResponse, cache$1, message, refs, success;
      cache$1 = response;
      refs = cache$1.refs;
      body = cache$1.body;
      success = cache$1.success;
      message = cache$1.message;
      if (success) {
        breakpointResponse = {
          breakpointId: body.breakpoint.toString(),
          locations: body.actual_locations.map(function (l) {
            return {
              scriptId: l.script_id.toString(),
              lineNumber: l.line,
              columnNumber: l.column
            };
          })
        };
        return cb(null, breakpointResponse);
      } else {
        return cb(ErrorObjectFromMessage(options)(refs)(message));
      }
    });
  };
  return setbreakpoint;
};
